apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter-svc
  namespace: nginx
  labels:
    app: nginx-exporter
spec:
  selector:
    app: nginx-exporter
  type: ClusterIP
  ports:
    - name: exporter
      protocol: TCP
      port: 9113
